M48
; DRILL file {KiCad (6.0.10-0)} date Friday, 17 February 2023 at 15:47:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T15:47:39-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X4.5Y-2.9
X4.5Y-3.5
X4.6Y-2.6
X4.6Y-3.5
X4.8Y-3.2
X4.8Y-3.4
X4.9Y-3.2
X5.0Y-2.8
X5.0Y-2.9
X5.0Y-3.0
X5.1Y-2.8
X5.1Y-3.0
T2
X4.8Y-2.6
X5.0Y-2.6
T0
M30
